pipeline {
  agent {
    node {
      label 'imagebuild'
    }
  }
  stages {
    stage('Checkout GitSCM') {
      steps {
      checkout([$class: 'GitSCM', branches: [[name: '**']], extensions: [[$class: 'PerBuildTag']],
                userRemoteConfigs: [[url: 'https://github.com/qdzlug/nginxplus-img']]])
      }
    }

    stage('Configure Environment') {
      steps {
        sh '''sudo apt -y install virtualenvwrapper qemu-utils python3-diskimage-builder gpg-agent
        virtualenv $WORKSPACE/dib-elements
        . $WORKSPACE/dib-elements/bin/activate
        pip install diskimage-builder
        '''
      }
    }

    stage('Build SSH Keys') {
      steps {
        sh '''
        # Make sure the directory is clean...
        rm $WORKSPACE/debian/elements/nginx-plus/static/root/.ssh/* || true
        ssh-keygen -t ed25519 -a 100 -N ''  -C nginxplus_sync -f $WORKSPACE/debian/elements/nginx-plus/static/root/.ssh/id_rsa
        KEY=$(cat $WORKSPACE/debian/elements/nginx-plus/static/root/.ssh/id_rsa.pub)
        echo 'from="169.254.0.1,169.254.0.2"' $KEY > $WORKSPACE/debian/elements/nginx-plus/static/root/.ssh/authorized_keys
        '''
      }
    }

    stage('Write Build Information') {
      steps {
        sh '''
        # Write out build information
        JENKINS_TXT=$WORKSPACE/ubuntu/elements/nginx-plus/static/etc/jenkins.txt
        echo "=============================================================" > $JENKINS_TXT
        echo Build $BUILD_TAG at `date` >> $JENKINS_TXT
        echo Github URL: $GIT_URL >> $JENKINS_TXT
        echo Branch: $GIT_BRANCH >> $JENKINS_TXT
        echo Commit: $GIT_COMMIT >> $JENKINS_TXT
        echo "=============================================================" >> $JENKINS_TXT
        # Copy over the documentation
        cp $WORKSPACE/docs/Usage.md $WORKSPACE/ubuntu/nginx-plus/static/root/Usage.md
        '''
      }
    }

    stage('Build Image') {
      steps {
       configFileProvider([configFile(fileId: '0a0b590a-38b6-44b1-988c-1fd78d4fd7fc', targetLocation: 'debian/elements/nginx-plus/static/etc/ssl/nginx/nginx-repo.crt',
                           variable: 'NGINX_CERT'), configFile(fileId: 'e8bd0df6-0d9a-4564-b36c-844afd6c64d0',
                           targetLocation: 'debian/elements/nginx-plus/static/etc/ssl/nginx/nginx-repo.key', variable: 'NGINX_KEY')])
        {
          sh '''
          . $WORKSPACE/dib-elements/bin/activate
          export DIB_DHCP_NETWORK_MANAGER_AUTO=true
          export DIB_RELEASE=bullseye
          export DIB_DEBUG_TRACE=1
          export ELEMENTS_PATH=$WORKSPACE/debian/elements
          disk-image-create -a amd64 -o nginxplus-debian-$BUILD_ID.qcow2 block-device-mbr nginx-plus
          '''
        }
      }
    }

    stage('Archive Image') {
        steps {
          archiveArtifacts artifacts: '*.qcow2', fingerprint: true, followSymlinks: false, onlyIfSuccessful: true
        }
    }

    stage('Clean Workspace') {
       steps {
         cleanWs()
    }
   }
  }
}